language: c

sudo: required

services:
  - docker

install:
  - docker build . -t sshaddicts/crossbar-for-neuralswarm

script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
